name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to EC2 server
      - name: 📂 Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          protocol: ftp
          port: 21

      # Step 3: Execute remote SSH commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the Laravel project directory
            cd /home/dioomyid/cinelounge.dioo.my.id
            
            # Copy .env.example to .env
            cp .env.example .env
            
            # Update .env with environment variables
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_FROM_ADDRESSE=${{ secrets.MAIL_USERNAME }}" >> .env
            
            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Clear all caches first
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            
            # Generate key if needed
            php artisan key:generate
            
            # Optimize and cache
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache